services:
  postgres:
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    user: "${UID}:${GID}"
